version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
      
  redis:
    image: redis:3.2  
    ports:
      - "6379:6379"
      
  webapi:
    build: .
    depends_on:
      - postgres
      - redis
      
    environment:
        - "Database:ConnectionString=Host=postgres;Port=5432;Database=usersdb;Username=postgres;Password=docker"
        - "Cache:ConnectionString=redis"
    ports:
      - "5000:80"