version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
      
  redis:
    image: redis:3.2  
    ports:
      - "6379:6379"
      
  webapi:
    build: .
    ports:
      - "5003:80"